directories:
  output: .
  buildResources: build
appId: com.reeceyboin.popquiz
productName: PopQuiz
copyright: Copyright © 2025 Reece N
files:
  - filter:
      - electron/**/*
      - dist/**/*
      - dist-player/**/*
      - package.json
extraResources:
  - from: resorces/sounds/Misc
    to: sounds/Misc
  - from: resorces/sounds/Applause
    to: sounds/Applause
  - from: resorces/sounds/Countdown
    to: sounds/Countdown
  - from: resorces/sounds/Fail Sounds
    to: sounds/Fail Sounds
  - from: resorces/sounds/Buzzers
    to: sounds/Buzzers
asar: true
win:
  target:
    - target: portable
      arch:
        - x64
  icon: build/icon.ico
  artifactName: PopQuiz.exe
electronVersion: 38.7.2
